;ROIRange=(ColStartPos, RowStartPos, ColEndPos, RowEndPos)
;Binning value:0,1
;image size depends on Binning & ROIRange;
;image width=(ColEndPos-ColStartPos+1) / (Binning+1)
;image height= (RowEndPos-RowStartPos+1) / (Binning+1)
;-------Notice-----
;   1.image width must not be less than 256; 

[ApplicationMode1]
FullWell=1
Binning=0
Frequency=18
ROIRange=(0, 70, 4680, 1475)
subset=Mode1

[ApplicationMode2]
FullWell=1
Binning=1
Frequency=36
ROIRange=(0, 70, 4680, 1475)
subset=Mode2
