;binning    size
;   0      3072 X 3060
;   1      1536 X 1530
;   2      1024 X 1020
;   3       768 X 765
;-------------
;Note:If ApplicationModeX and ApplicationModeY has the same PGA and Binning value, 
;     the subset can be set to ModeN-X and ModdeN-Y, eg.
;[ApplicationMode1]
;PGA=2
;Binning=0
;Frequency=10
;ROIRange=(0, 0, 3071, 3071)
;subset=Mode1-1
;
;[ApplicationMode2]
;PGA=2
;Binning=0
;Frequency=15
;ROIRange=(0, 0, 3071, 3071)
;subset=Mode1-2

;ExposureMode--Dynamic(Pulse:128,Continues:129,Flush:131)
[ApplicationMode1]
PGA=2
Binning=0
Frequency=15
ROIRange=(0, 6, 3071, 3065)
ExposureMode=129
subset=Mode1

[ApplicationMode2]
PGA=2
Binning=1
Frequency=20
ROIRange=(0, 6, 3071, 3065)
ExposureMode=129
subset=Mode2

[ApplicationMode3]
PGA=2
Binning=2
Frequency=6
ROIRange=(0, 6, 3071, 3065)
ExposureMode=129
subset=Mode3

[ApplicationMode4]
PGA=2
Binning=3
Frequency=6
ROIRange=(0, 6, 3071, 3065)
ExposureMode=129
subset=Mode4
