;ROIRange=(ColStartPos, RowStartPos, ColEndPos, RowEndPos)
;Binning value:0(1x1)
;              1(2x2)
;image size depends on Binning & ROIRange;
;image width=(ColEndPos-ColStartPos+1) / (Binning + 1)
;image height= (RowEndPos-RowStartPos+1) / (Binning + 1)
;-------Notice-----
;   1.image width must not be less than 256; 

;ExposureMode--Pulse:128,Continues:129
[ApplicationMode1]
PGA=2
Binning=0
ROIRange=(0, 0, 767, 767)
Frequency=20
ExposureMode=129
subset=Mode1

[ApplicationMode2]
PGA=3
Binning=1
ROIRange=(0, 0, 767, 767)
Frequency=30
ExposureMode=129
subset=Mode2

