[offset]
Cfg_Base=100
Cfg_PreOffsetTotalFrames=4
Cfg_PreOffsetTotalFrames_dynamic=32

[gain]
Cfg_CalcGainValueByMedian=1
Cfg_MaxGainFramesInPoint=5
Cfg_MaxMultiGainFramesInPoint=19
Cfg_MultiGainPoints_Stage1=2500
Cfg_MultiGainPoints_Stage2=3500
Cfg_MultiGainPoints_Stage3=4500
Cfg_MultiGainPoints_Stage4=5400
Cfg_MultiGainPoints_Stage5=7100
Cfg_MultiGainPoints_Stage6=18000
Cfg_MultiGainPoints_Stage7=20000
Cfg_MultiGainPoints_Stage8=23000
Cfg_MultiGainPoints_Stage9=26000
Cfg_MultiGainPoints_Stage10=29000
Cfg_MultiGainPoints_Stage11=32000
Cfg_MultiGainPoints_Stage12=36000
Cfg_MultiGainPoints_Stage13=40000

[defect]
Cfg_FindMethod=2
Cfg_DoseCount=1
Cfg_DoseCount_dynamic=3
Cfg_FramesOfHighestDose=8
Cfg_FramesOfHighestDose_dynamic=19
Cfg_MaxBadPointsInLinePercent=25
Cfg_DummyLineTop=5
Cfg_DummyLineBottom=5
Cfg_DummyLineLeft=5
Cfg_DummyLineRight=5
Cfg_StdHardCut1Min=500
Cfg_StdHardCut1Max=65000
Cfg_StdWeakCut1Min=0.01
Cfg_StdWeakCut1Max=6.0
Cfg_StdWeakCut2Min=0.01
Cfg_StdWeakCut2Max=6.0
Cfg_StdWeakCut3Min=6.0
Cfg_StdWeakCut3Max=6.0
Cfg_StdWeakCut4Min=6.0
Cfg_StdWeakCut4Max=6.0
Cfg_StdWeakCut5Min=7.0
Cfg_StdWeakCut5Max=7.0
Cfg_StdWeakCut6Min=6.0
Cfg_StdWeakCut6Max=6.0
Cfg_WeakCut6KeepGateDividerGood=1
#Cfg_WeakCut6DummyTop=0
#Cfg_WeakCut6DummyBottom=0
#Cfg_WeakCut6DummyLeft=0
#Cfg_WeakCut6DummyRight=0
Cfg_GridLength=128
Cfg_DummyLineTop2=0
Cfg_DummyLineBottom2=0
Cfg_DummyLineLeft2=0
Cfg_DummyLineRight2=0
Cfg_StdHardCut1Min2=500
Cfg_StdHardCut1Max2=65000
Cfg_StdWeakCut1Min2=0.01
Cfg_StdWeakCut1Max2=6.0
Cfg_StdWeakCut2Min2=0.05
Cfg_StdWeakCut2Max2=6.0
Cfg_StdWeakCut3Min2=6.0
Cfg_StdWeakCut3Max2=6.0

[clipping]
Cfg_EnableClipping=1
Cfg_ClippingValue=40000

[else]
Cfg_EnableDynLag=0
Cfg_EnableCalcAvgValueOfImage=0

