;Note:If ApplicationModeX and ApplicationModeY has the same PGA and Binning value, 
;     the subset can be set to ModeN-X and ModdeN-Y, eg.
;[ApplicationMode1]
;PGA=2
;Binning=2
;Frequency=5
;Zoom=0
;subset=Mode1-1
;
;[ApplicationMode2]
;PGA=2
;Binning=2
;Frequency=8
;Zoom=0
;subset=Mode1-2
;
;[ApplicationMode3]
;PGA=2
;Binning=2
;Frequency=10
;Zoom=0
;subset=Mode1-3

;ExposureMode--Continues:129;
[ApplicationMode1]
PGA=5
Binning=0
Frequency=2
Zoom=0
ExposureMode=129
ClippingValue=40000
subset=Mode1

