[offset]
Cfg_Base=100
Cfg_PreOffsetTotalFrames=32

[gain]
Cfg_CalcGainValueByMedian=1

[defect]
Cfg_FindMethod=2
Cfg_DoseCount=1
Cfg_DoseCount_dynamic=3
Cfg_FramesOfHighestDose=8
Cfg_FramesOfHighestDose_dynamic=19
Cfg_MaxBadPointsInLinePercent=20
Cfg_DummyLineTop=0
Cfg_DummyLineBottom=0
Cfg_DummyLineLeft=0
Cfg_DummyLineRight=0
Cfg_StdHardCut1Min=500
Cfg_StdHardCut1Max=65000
Cfg_StdWeakCut1Min=0.01
Cfg_StdWeakCut1Max=5.0
Cfg_StdWeakCut2Min=0.01
Cfg_StdWeakCut2Max=5.0
Cfg_StdWeakCut3Min=6.0
Cfg_StdWeakCut3Max=6.0
Cfg_StdWeakCut4Min=6.0
Cfg_StdWeakCut4Max=6.0
Cfg_StdWeakCut5Min=7.0
Cfg_StdWeakCut5Max=7.0
Cfg_StdWeakCut6Min=6.0
Cfg_StdWeakCut6Max=6.0
#Cfg_WeakCut6DummyTop=0
#Cfg_WeakCut6DummyBottom=0
#Cfg_WeakCut6DummyLeft=0
#Cfg_WeakCut6DummyRight=0
Cfg_GridLength=128
Cfg_DummyLineTop2=0
Cfg_DummyLineBottom2=0
Cfg_DummyLineLeft2=0
Cfg_DummyLineRight2=0
Cfg_StdHardCut1Min2=500
Cfg_StdHardCut1Max2=65000
Cfg_StdWeakCut1Min2=0.01
Cfg_StdWeakCut1Max2=6.0
Cfg_StdWeakCut2Min2=0.01
Cfg_StdWeakCut2Max2=6.0
Cfg_StdWeakCut3Min2=6.0
Cfg_StdWeakCut3Max2=6.0
Cfg_DefectMethod=0

[clipping]
Cfg_EnableClipping=1
Cfg_ClippingValue=60000

[else]
Cfg_EnableCalcAvgValueOfImage=0
