;binning zoom    size
;   0     0    4352 X 3072
;   0     8    3072 X 3072
;   0     9    2048 X 2048
;   1     0    2176 X 1536
;   1     11   1024 X 1024
;   2     8    1024 X 1024
;   5     8    512 X 512  
;-------------
;Note:If ApplicationModeX and ApplicationModeY has the same PGA and Binning value, 
;     the subset can be set to ModeN-X and ModdeN-Y, eg.
;[ApplicationMode1]
;PGA=2
;Binning=0
;Frequency=10
;Zoom=0
;subset=Mode1-1
;
;[ApplicationMode2]
;PGA=2
;Binning=0
;Frequency=10
;Zoom=0
;subset=Mode1-2
;
;[ApplicationMode3]
;PGA=2
;Binning=0
;Frequency=15
;Zoom=0
;subset=Mode1-3

;ExposureMode--Pulse:128,Continues:129,Flush:131
[ApplicationMode1]
PGA=6
Binning=0
ROIRange=(0, 0, 4351, 3071)
Frequency=4
ExposureMode=129
subset=Mode1

[ApplicationMode2]
PGA=3
Binning=1
ROIRange=(0, 0, 4351, 3071)
Frequency=15
ExposureMode=129
subset=Mode2

[ApplicationMode3]
PGA=3
Binning=2
ROIRange=(0, 0, 4351, 3071)
Frequency=35
ExposureMode=129
subset=Mode3

[ApplicationMode4]
PGA=3
Binning=3
ROIRange=(0, 0, 4351, 3071)
Frequency=45
ExposureMode=129
subset=Mode4
