[offset]
Cfg_Base=100
Cfg_PreOffsetTotalFrames=32

[gain]
Cfg_CalcGainValueByMedian=1
Cfg_MaxMultiGainFramesInPoint=10
;Cfg_IgnoreNumbers=5
;Cfg_MultiGainPoints_ExpectedFrames=5,5,5,5,5,5,5,5,5,5,5,5,5,5
;Cfg_MultiGainPoints_ClearFrames=2,2,2,2,2,2,2,2,2,2,2,2,2,2
Cfg_MultiGainPoints_Stage1=1000,1500,2000,2500,3000,5000,7500
Cfg_MultiGainPoints_Stage2=10000,15000,20000,25000,30000,35000,40000
Cfg_MethodOfMultiGain=1

[defect]
Cfg_FindMethod=0
Cfg_DoseCount=3
Cfg_FramesOfHighestDose=19
Cfg_MaxBadPointsInLinePercent=25
Cfg_DummyLineTop=0
Cfg_DummyLineBottom=0
Cfg_DummyLineLeft=0
Cfg_DummyLineRight=0
Cfg_StdHardCut1Min=100
Cfg_StdHardCut1Max=65000
Cfg_StdWeakCut1Min=0.01
Cfg_StdWeakCut1Max=6.0
Cfg_StdWeakCut2Min=0.01
Cfg_StdWeakCut2Max=6.0
Cfg_StdWeakCut3Min=43
Cfg_StdWeakCut3Max=12
Cfg_StdWeakCut4Min=6.0
Cfg_StdWeakCut4Max=6.0
Cfg_StdWeakCut5Min=7.0
Cfg_StdWeakCut5Max=7.0
Cfg_StdWeakCut6Min=6.0
Cfg_StdWeakCut6Max=6.0
#Cfg_WeakCut6DummyTop=0
#Cfg_WeakCut6DummyBottom=0
#Cfg_WeakCut6DummyLeft=1
#Cfg_WeakCut6DummyRight=1
Cfg_GridLengthX=195
Cfg_GridLengthY=246
Cfg_DummyLineTop2=0
Cfg_DummyLineBottom2=0
Cfg_DummyLineLeft2=1
Cfg_DummyLineRight2=1
Cfg_StdHardCut1Min2=100
Cfg_StdHardCut1Max2=65000
Cfg_StdWeakCut1Min2=0.01
Cfg_StdWeakCut1Max2=6.0
Cfg_StdWeakCut2Min2=0.01
Cfg_StdWeakCut2Max2=6.0
Cfg_StdWeakCut3Min2=8.0
Cfg_StdWeakCut3Max2=8.0
Cfg_MaxCountOfTooHigh=50000

[clipping]
Cfg_EnableClipping=1
Cfg_ClippingValue=45000

[else]
Cfg_EnableCalcAvgValueOfImage=0
Cfg_EnableDenoise=1