;binning zoom    size
;   0     0    8704 X 3072
;-------------
;Note:If ApplicationModeX and ApplicationModeY has the same PGA and Binning value, 
;     the subset can be set to ModeN-X and ModdeN-Y, eg.
;[ApplicationMode1]
;PGA=2
;Binning=0
;Frequency=10
;Zoom=0
;subset=Mode1-1
;
;[ApplicationMode2]
;PGA=2
;Binning=0
;Frequency=10
;Zoom=0
;subset=Mode1-2
;
;[ApplicationMode3]
;PGA=2
;Binning=0
;Frequency=15
;Zoom=0
;subset=Mode1-3

;ExposureMode--Manual:1,AEC:2, Pulse:128,Continues:129,Flush:131
[ApplicationMode1]
PGA=6
Binning=0
ROIRange=(0, 0, 8703, 3071)
Frequency=2
ExposureMode=129
subset=Mode1

[ApplicationMode2]
PGA=6
Binning=1
ROIRange=(0, 0, 8703, 3071)
Frequency=8
ExposureMode=129
subset=Mode2

[ApplicationMode3]
PGA=6
Binning=2
ROIRange=(0, 0, 8703, 3071)
Frequency=10
ExposureMode=129
subset=Mode3
