;ROIRange=(ColStartPos, RowStartPos, ColEndPos, RowEndPos)
;Binning value:0(1x1)
;              1(2x2)
;              129(1x2)

;Digital Binning: 201(1.33x1.33)  

;image size depends on Binning & ROIRange;
;image width=(ColEndPos-ColStartPos+1) / (Binning + 1)
;image height= (RowEndPos-RowStartPos+1) / (Binning + 1)
;-------Notice-----
;   1.image width must not be less than 256; 

;ExposureMode--Flush:131,Manual2:4,Pulse:128,Continues:129
[ApplicationMode1]
PGA=4
Binning=0
ROIRange=(0, 0, 3455, 3071)
Frequency=5
ExposureMode=129
subset=Mode1