;ROIRange=(ColStartPos, RowStartPos, ColEndPos, RowEndPos)
;Binning value:0,1
;image size depends on Binning & ROIRange;
;image width=(ColEndPos-ColStartPos+1) / (Binning+1)
;image height= (RowEndPos-RowStartPos+1) / (Binning+1)
;-------Notice-----
;   1.image width must not be less than 256; 

[ApplicationMode1]
FullWell=1
Binning=0
Frequency=9
ROIRange=(780, 70, 1949, 1475)
subset=Mode1


