;Note:If ApplicationModeX and ApplicationModeY has the same PGA and Binning value, 
;     the subset can be set to ModeN-X and ModdeN-Y, eg.
; [ApplicationMode1]
; PGA=3
; Binning=0
; Frequency=10
; subset=Mode1-1

; [ApplicationMode2]
; PGA=3
; Binning=0
; Frequency=20
; subset=Mode1-2

;ExposureMode--Pulse:128,Continues:129,Flush:131
[ApplicationMode1]
PGA=6
Binning=0
Frequency=7.5
ExposureMode=129
ROIRange=(0, 0, 4266, 4266)
subset=Mode1